#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: cms-pv
#spec:
#  capacity:
#    storage: 100Gi
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: "ceph-filesystem"
#  hostPath:
#    path: /storage/volumes/incheon-airport/dev/cms/contents_root
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-pvc
  namespace: croms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ceph-filesystem"
  resources:
    requests:
      storage: 100Gi
