{{- if .Values.global.deployConfigs }}

# =================================================================
# Global ConfigMap
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  TIMEZONE: "Asia/Seoul"
  ACTION_PROFILE: "k8s"
  ALLOW_ORIGIN: "http://localhost:8700,http://localhost:8701,http://localhost:8080,http://localhost,*"
  DOWNLOAD_URL: "http://10.40.16.50/upload/"
  HEARTBEAT_INTERVAL: "30000"

---

# =================================================================
# MariaDB ConfigMap
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  DATASOURCE_URL: "jdbc:mysql://10.40.16.22:3306,10.40.16.23:3306,10.40.16.24:3306/croms?serverTimezone=Asia/Seoul&connectTimeout=15000&socketTimeout=60000&retriesAllDown=3&tcpKeepAlive=true&allowMultiQueries=true&loadBalance=true&sessionVariables=wsrep_sync_wait=1"
  DATABASE: "croms"
  USERNAME: "cromsDb@clobot-mysql"
---

# =================================================================
# Secrets (MariaDB, Redis, Elasticsearch, RabbitMQ, EMQX, Registry)
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  ROOT_PASSWORD: "croms123!@"
  PASSWORD: "croms123!@#"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  PASSWORD: "test1234!@!@"
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  USERNAME: "elastic"
  PASSWORD: "Ain7RE3QcwexSov8cTw7"
  ES_DISCOVERY_SEED_HOSTS: "elasticsearch-0.elasticsearch-headless,elasticsearch-1.elasticsearch-headless,elasticsearch-2.elasticsearch-headless"
  ES_INITIONAL_MASTER_NODES: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
  ES_JAVA_OPTS: "-Xms8g -Xmx8g"
  ES_REPLICA_COUNTS: "3"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "croms"
  RABBITMQ_DEFAULT_PASS: "enemfu1*"
  RABBITMQ_DEFAULT_VHOST: "croms-device"
  ERLANG_COOKIE: "XJFKDLS9283JKLQWERTYZXCVBNM"
---
apiVersion: v1
kind: Secret
metadata:
  name: emqx-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  USERNAME: "cloud"
  PASSWORD: "zmfhatm*0"
  DASHBOARD_USERNAME: "clobot"
  DASHBOARD_PASSWORD: "ansdufdj1*"
  ERLANG_COOKIE: AidlscjsrhdgkdClobotCroms
---
apiVersion: v1
kind: Secret
metadata:
  name: croms-registry-cred
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbG9ib3QuY28ua3IiOnsidXNlcm5hbWUiOiJjcm9tcy1kZXZAY2xvYm90LmNvLmtyIiwicGFzc3dvcmQiOiJtYXh4aWt4VVp0Zzh0S1RuYWhEeiIsImVtYWlsIjoiY3JvbXMtZGV2QGNsb2JvdC5jby5rciIsImF1dGgiOiJZM0p2YlhNdFpHVjJRR05zYjJKdmRDNWpieTVyY2pwdFlYaDRhV3Q0VlZwMFp6aDBTMVJ1WVdoRWVnPT0ifX19

{{- end }}
