{{- if .Values.elasticsearch.enabled }}

# =================================================================
# Elasticsearch Services (ClusterIP and Headless)
# =================================================================
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: 9300

---

# =================================================================
# Elasticsearch StatefulSet
# =================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  serviceName: "elasticsearch-headless"
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: docker.io/library/busybox:1.31.1
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map-count
        image: docker.io/library/busybox:1.31.1
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-container
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - name: rest
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ES_DISCOVERY_SEED_HOSTS
        - name: cluster.initial_master_nodes
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: ES_INITIONAL_MASTER_NODES
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: PASSWORD
        - name: "ES_JAVA_OPTS"
          value: "-Xms8g -Xmx8g"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: TIMEZONE
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.elasticsearch.storage.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.elasticsearch.storage.size }}
{{- end }}