{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: croms-ingress-{{ .Release.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: croms-core-service
            port:
              number: 9195
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: croms-auth-service
            port:
              number: 9194
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: croms-core-service
            port:
              number: 9195
      - path: /
        pathType: Prefix
        backend:
          service:
            name: croms-front-service
            port:
              number: 80
{{- end }}