{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.cluster) }}
# =================================================================
# RabbitMQ Headless Service (StatefulSet용)
# =================================================================
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
spec:
  clusterIP: None # ★★★ Headless Service로 만들기 위한 핵심 설정
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: http-stats
---
# =================================================================
# RabbitMQ StatefulSet
# =================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq-headless" # ★★★ Headless Service 이름과 일치
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-container
        image: "rabbitmq:3.11.11-management"
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: "croms-device"
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER # configs-and-secrets-manifest.yaml과 일치
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS # configs-and-secrets-manifest.yaml과 일치
        - name: RABBITMQ_ERLANG_COOKIE
          value: "THIS_IS_A_SECRET_COOKIE_CHANGE_IT" # 임의의 값
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 10Gi
{{- end }}