# =================================================================
# Global ConfigMap
# 여러 애플리케이션에서 공통으로 사용하는 비민감성 설정 정보를 저장합니다.
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: croms
data:
  TIMEZONE: "Asia/Seoul"
  ACTION_PROFILE: "k8s"
  ALLOW_ORIGIN: "http://localhost:8700,http://localhost:8701,http://localhost:8080,http://localhost,*"
  DOWNLOAD_URL: "http://10.40.16.50/upload/"
  HEARTBEAT_INTERVAL: "30000"

---

# =================================================================
# MariaDB ConfigMap
# MariaDB 접속에 필요한 민감한 정보(비밀번호 등)를 저장합니다.
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: croms
data:                       # 데이터를 Base64 인코딩 없이 평문으로 편리하게 입력할 수 있습니다.
  DATASOURCE_URL: "jdbc:mysql://10.40.16.22:3306,10.40.16.23:3306,10.40.16.24:3306/croms?serverTimezone=Asia/Seoul&connectTimeout=15000&socketTimeout=60000&retriesAllDown=3&tcpKeepAlive=true&allowMultiQueries=true&loadBalance=true&sessionVariables=wsrep_sync_wait=1"
  # DATASOURCE_URL: "jdbc:mysql://10.40.16.22:3306/croms?serverTimezone=Asia/Seoul&connectTimeout=15000&socketTimeout=60000&retriesAllDown=3&tcpKeepAlive=true&allowMultiQueries=true&loadBalance=true&sessionVariables=wsrep_sync_wait=1"
  DATABASE: "croms"
  USERNAME: "cromsDb@clobot-mysql"
---

# =================================================================
# MariaDB Secret
# MariaDB 접속에 필요한 민감한 정보(비밀번호 등)를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: croms
type: Opaque                     # 키-값 형태의 데이터를 저장하는 가장 일반적인 Secret 타입
stringData:                       # 데이터를 Base64 인코딩 없이 평문으로 편리하게 입력할 수 있습니다.
  ROOT_PASSWORD: "croms123!@"
  PASSWORD: "croms123!@#"

---

# =================================================================
# Redis Secret
# Redis 접속에 필요한 비밀번호를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: croms
type: Opaque
stringData:
  PASSWORD: "test1234!@!@"

---

# =================================================================
# Elasticsearch Secret
# Elasticsearch 접속에 필요한 사용자 이름과 비밀번호를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: croms
type: Opaque
stringData:
  USERNAME: "elastic"
  PASSWORD: "Ain7RE3QcwexSov8cTw7"
  ES_DISCOVERY_SEED_HOSTS: "elasticsearch-0.elasticsearch-headless,elasticsearch-1.elasticsearch-headless,elasticsearch-2.elasticsearch-headless"
  ES_INITIONAL_MASTER_NODES: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
  ES_JAVA_OPTS: "-Xms8g -Xmx8g"
  ES_REPLICA_COUNTS: "3"

---

# =================================================================
# RabbitMQ Secret
# RabbitMQ 접속에 필요한 사용자 이름과 비밀번호를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: croms
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "croms"
  RABBITMQ_DEFAULT_PASS: "enemfu1*"
  RABBITMQ_DEFAULT_VHOST: "croms-device"
  ERLANG_COOKIE: "XJFKDLS9283JKLQWERTYZXCVBNM"

---

# =================================================================
# EMQX Secret
# EMQX(MQTT 브로커) 접속 및 대시보드 로그인에 필요한 정보를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: emqx-secret
  namespace: croms
type: Opaque
stringData:
  USERNAME: "cloud"
  PASSWORD: "zmfhatm*0"
  DASHBOARD_USERNAME: "clobot"
  DASHBOARD_PASSWORD: "ansdufdj1*"
  ERLANG_COOKIE: AidlscjsrhdgkdClobotCroms

---

# =================================================================
# Private Docker Registry Secret
# 비공개 Docker 레지스트리에서 컨테이너 이미지를 다운로드하기 위한 인증 정보를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: croms-registry-cred
  namespace: croms
type: kubernetes.io/dockerconfigjson # Docker 인증 정보를 위한 전용 Secret 타입
data:
  # .dockerconfigjson 키에는 Docker 설정 파일(~/.docker/config.json)의 내용을 Base64로 인코딩한 값이 들어갑니다.
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbG9ib3QuY28ua3IiOnsidXNlcm5hbWUiOiJjcm9tcy1kZXZAY2xvYm90LmNvLmtyIiwicGFzc3dvcmQiOiJtYXh4aWt4VVp0Zzh0S1RuYWhEeiIsImVtYWlsIjoiY3JvbXMtZGV2QGNsb2JvdC5jby5rciIsImF1dGgiOiJZM0p2YlhNdFpHVjJRR05zYjJKdmRDNWpieTVyY2pwdFlYaDRhV3Q0VlZwMFp6aDBTMVJ1WVdoRWVnPT0ifX19
