# =================================================================
# Global & Environment Specific Configuration
# =================================================================
global:
  # 'croms-dev' 또는 테스트용 새 네임스페이스 지정
  namespace: "helm-test-ns"
  registry: "registry.clobot.co.kr/croms/edge/croms-incheon-airport-k8s"
  pullPolicy: IfNotPresent
  # ConfigMap과 Secret을 배포하도록 활성화
  deployConfigs: true 

# =================================================================
# Ingress Settings
# =================================================================
ingress:
  enabled: true
  className: "nginx"
  # 로컬 환경에서 사용할 도메인
  host: "k8s-test-croms.co.kr" 
  # HTTPS 사용 시 TLS Secret 이름 (로컬에서는 주석 처리)
  # tlsSecretName: croms-tls-secret 

# =================================================================
# Application Services (배포할 핵심 애플리케이션)
# =================================================================
cromsAuth:
  enabled: true
  image:
    repository: "croms-auth-server"
    tag: "0702a7f2"

cromsCore:
  enabled: true
  image:
    repository: "croms-core-server"
    tag: "0702a7f2"

cromsFront:
  enabled: true
  image:
    repository: "croms-front-end"
    tag: "0702a7f2"

# =================================================================
# Infrastructure Services (★ 로컬 환경용 단일 노드 구성 ★)
# 모든 cluster 설정을 false로 변경하고 replicaCount를 1로 고정합니다.
# =================================================================
rabbitmq:
  enabled: true
  cluster: false # <-- 클러스터 모드 비활성화
  replicaCount: 1
  image:
    repository: "rabbitmq"
    tag: "3.11.11-management"
  storage:
    storageClassName: "nfs-client" # 현재 운영중인 storageClass
    size: 10Gi

redis:
  enabled: true
  cluster: false # <-- 클러스터 모드 비활성화
  replicaCount: 1
  image:
    repository: "redis/redis-stack"
    tag: "7.2.0-v10"
  storage:
    storageClassName: "nfs-client"
    size: 5Gi

emqx:
  enabled: true
  cluster: false # <-- 클러스터 모드 비활성화
  replicaCount: 1
  image:
    repository: "emqx/emqx"
    tag: "4.3.22"
  storage:
    storageClassName: "nfs-client"
    size: 5Gi

elasticsearch:
  enabled: true
  replicaCount: 1
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch"
    tag: "7.9.1"
  storage:
    storageClassName: "nfs-client"
    size: 20Gi
  javaOpts: "-Xms1g -Xmx1g" # 로컬 환경에 맞게 메모리 조정

# =================================================================
# UI & Other Tools
# =================================================================
kibana:
  enabled: true
  image:
    repository: "docker.elastic.co/kibana/kibana"
    tag: "7.9.1"
  service:
    # Ingress를 통해 접근하므로 NodePort 불필요, ClusterIP로 변경
    type: ClusterIP 

# =================================================================
# Storage & PVCs (Croms 서비스용)
# =================================================================
storage:
  enabled: true
  storageClassName: "nfs-client"
  croms:
    uploadSize: 5Gi
    coreLogsSize: 5Gi
    authLogsSize: 5Gi