{{- if .Values.front.enabled }}

# =================================================================
# Apache SSL/Proxy ConfigMap
# croms-front-service (Apache) 컨테이너에서 사용할 httpd-ssl.conf 설정을 정의합니다.
# API, WebSocket 등에 대한 리버스 프록시 규칙이 포함되어 있습니다.
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-ssl-extra
data:
  httpd-ssl.conf: |
    <IfModule mod_ssl.c>
      # Listen 443
      # Listen 80

      <VirtualHost *:443>
        ServerName k8s-incheon-airport.croms.co.kr
        DocumentRoot "/opt/frontend/croms-web/croms-web"
        DirectoryIndex index.html

        SSLEngine on
        SSLCertificateFile /usr/local/apache2/ssl/server.crt
        SSLCertificateKeyFile /usr/local/apache2/ssl/server.key

        # ProxyPreserveHost On
        # ProxyRequests Off

        # ProxyPass /api/         http://croms-core-service:9195/api/
        # ProxyPassReverse /api/  http://croms-core-service:9195/api/
        # ProxyPass /oauth2/      http://croms-auth-service:9194/oauth2/
        # ProxyPassReverse /oauth2/ http://croms-auth-service:9194/oauth2/
        # ProxyPass /websocket/   ws://croms-core-service:9195/websocket/
        # ProxyPassReverse /websocket/ ws://croms-core-service:9195/websocket/

        <LocationMatch "^/(?!api/|oauth2/|websocket/).*">
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^/(.*)$ /index.html [L]
        </LocationMatch>

        <Directory "/opt/frontend/croms-web">
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
        </Directory>

        ErrorLog /proc/self/fd/2
        CustomLog /proc/self/fd/1 combined
      </VirtualHost>

      <VirtualHost *:80>
        ServerName k8s-incheon-airport.croms.co.kr
        DocumentRoot "/opt/frontend/croms-web/croms-web"
        DirectoryIndex index.html
        # ProxyPreserveHost On
        # ProxyRequests Off
        # ProxyPass /        http://127.0.0.1:80/
        # ProxyPassReverse / http://127.0.0.1:80/
        RewriteEngine On
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -f [OR]
        RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
        RewriteRule ^ - [L]
        RewriteRule ^ /index.html [L]
      </VirtualHost>
    </IfModule>
{{- end }}


---

{{- if .Values.auth.enabled }}

# =================================================================
# Auth Service Application Properties ConfigMap
# (참고) 이 ConfigMap은 현재 croms-auth-deployment에서 사용되지 않고 있습니다.
# Deployment가 환경 변수 대신 이 설정을 사용하도록 수정할 수 있습니다.
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-app-properties
data:
  application.properties: |
    # Database Configuration
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.datasource.url=jdbc:mysql://mariadb-service:3306/croms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    spring.datasource.username=cromsDb
    spring.datasource.hikari.maximum-pool-size=20
    spring.datasource.hikari.minimum-idle=5
    spring.datasource.hikari.idle-timeout=300000

    # Redis Configuration
    spring.redis.host=redis-stack-service.croms.svc.cluster.local
    spring.redis.port=6379
    spring.redis.database=0
    spring.redis.timeout=2000ms
    spring.redis.lettuce.pool.max-active=8
    spring.redis.lettuce.pool.max-idle=8
    spring.redis.lettuce.pool.min-idle=0

    # RabbitMQ Configuration
    spring.rabbitmq.host=rabbitmq-service
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=croms
    spring.rabbitmq.virtual-host=croms-device

    # Logging Configuration
    logging.level.kr.co.clobot=DEBUG
    logging.level.org.springframework.security=DEBUG
    logging.level.org.redisson=DEBUG

    # Actuator Health Endpoint 설정 추가
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always
    management.endpoints.web.base-path=/

{{- end }}
