{{- if .Values.global.deployConfigs }}

# =================================================================
# Global ConfigMap
# 여러 애플리케이션에서 공통으로 사용하는 비민감성 설정 정보를 저장합니다.
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  TIMEZONE: "Asia/Seoul"
  CROMS_ACTIVE_PROFILE: "single"
  CROMS_ALLOW_ORIGIN: "http://localhost:8700,http://localhost:8701,http://localhost:8080,http://localhost,*"

---

# =================================================================
# MariaDB Secret
# MariaDB 접속에 필요한 민감한 정보(비밀번호 등)를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque                     # 키-값 형태의 데이터를 저장하는 가장 일반적인 Secret 타입
stringData:                       # 데이터를 Base64 인코딩 없이 평문으로 편리하게 입력할 수 있습니다.
  ROOT_PASSWORD: "croms123!@"
  DATABASE: "croms"
  USERNAME: "cromsDb@clobot-mysql"
  PASSWORD: "croms123!@#"

---

# =================================================================
# Redis Secret
# Redis 접속에 필요한 비밀번호를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  type: Opaque
stringData:
  PASSWORD: "test1234!@!@"

---

# =================================================================
# Elasticsearch Secret
# Elasticsearch 접속에 필요한 사용자 이름과 비밀번호를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
type: Opaque
stringData:
  USERNAME: "elastic"
  PASSWORD: "Ain7RE3QcwexSov8cTw7"

---

# =================================================================
# RabbitMQ Secret
# RabbitMQ 접속에 필요한 사용자 이름과 비밀번호를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  USERNAME: "croms"
  PASSWORD: "enemfu1*"

---

# =================================================================
# EMQX Secret
# EMQX(MQTT 브로커) 접속 및 대시보드 로그인에 필요한 정보를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: emqx-secret
type: Opaque
stringData:
  USERNAME: "cloud"
  PASSWORD: "zmfhatm*0"
  DASHBOARD_USERNAME: "clobot"
  DASHBOARD_PASSWORD: "ansdufdj1*"

---

# =================================================================
# Private Docker Registry Secret
# 비공개 Docker 레지스트리에서 컨테이너 이미지를 다운로드하기 위한 인증 정보를 저장합니다.
# =================================================================
apiVersion: v1
kind: Secret
metadata:
  name: croms-registry-cred
type: kubernetes.io/dockerconfigjson # Docker 인증 정보를 위한 전용 Secret 타입
data:
  # .dockerconfigjson 키에는 Docker 설정 파일(~/.docker/config.json)의 내용을 Base64로 인코딩한 값이 들어갑니다.
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbG9ib3QuY28ua3IiOnsidXNlcm5hbWUiOiJjcm9tcy1kZXZAY2xvYm90LmNvLmtyIiwicGFzc3dvcmQiOiJtYXh4aWt4VVp0Zzh0S1RuYWhEeiIsImVtYWlsIjoiY3JvbXMtZGV2QGNsb2JvdC5jby5rciIsImF1dGgiOiJZM0p2YlhNdFpHVjJRR05zYjJKdmRDNWpieTVyY2pwdFlYaDRhV3Q0VlZwMFp6aDBTMVJ1WVdoRWVnPT0ifX19

{{- end }}
