{{- if or .Values.core.enabled .Values.front.enabled }}

# =================================================================
# CROMs Upload PVC (NFS-based)
# croms-front-service Pod들이 공유할 업로드 데이터 저장용 PVC입니다.
# NFS 기반의 StorageClass를 사용하여 ReadWriteMany 모드로 생성합니다.
# =================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: croms-upload-pvc
spec:
  accessModes:
    - ReadWriteMany # ⬅️ 여러 Pod가 동시 접근 가능하도록 변경
  storageClassName: "nfs-client" # ⬅️ NFS 스토리지 사용하도록 변경
  resources:
    requests:
      storage: 5Gi # 필요시 용량 조절

{{- end }}
